production:
  environment: production
  SMTP_USER: YOUR_SMTP_USER
  SMTP_PASSWORD: YOUR_SMTP_PASSWORD
  SMTP_ADDRESS: YOUR_SMTP_ADDRESS
  SMTP_PORT: YOUR_SMTP_PORT
development:
  environment: sandbox
  SMTP_USER: YOUR_SMTP_USER
  SMTP_PASSWORD: YOUR_SMTP_PASSWORD
  SMTP_ADDRESS: YOUR_SMTP_ADDRESS
  SMTP_PORT: YOUR_SMTP_PORT