# Rename this file to "smtp.yml" and replace the credentials below with your own SMTP settings
production:
  environment: production
  SMTP_USER: your_SMTP_email
  SMTP_PASSWORD: your_SMTP_password
  SMTP_ADDRESS: your_SMTP_address
  SMTP_PORT: your_SMTP_port
development:
  environment: sandbox
  SMTP_USER: your_SMTP_email
  SMTP_PASSWORD: your_SMTP_password
  SMTP_ADDRESS: your_SMTP_address
  SMTP_PORT: your_SMTP_port